export enum ReportType {
    SPAM = "SPAM",
    HARASSMENT = "HARASSMENT",
    INAPPROPRIATE = "INAPPROPRIATE",
    MISINFORMATION = "MISINFORMATION",
    COPYRIGHT_VIOLATION = "COPYRIGHT_VIOLATION",
    OTHER = "OTHER"
}
